### ISSUE TITLE
Undefined keysym 'Return'

### ISSUE THREAD

**Issue by ephemeralwaves** [dnschneid/mid2key#1]
When I run xev in the terminal and look up the enter key I get: keycode 36 (keysym 0xff0d, Return).  I've tried setting one of my midi keys to 'Return', '36' and even '0xff0d' all to no avail.  When I do the same for the space key it all seems to work fine. Am I missing something?

**Comment by aparks5** [comment]
same problem here, going to hunt this down and fix it

**Comment by aparks5** [comment]
ok the problem is that map only stores KeyCodes, and some keys have a key_sym_ higher than 256 but a keycode within that. the fix is to change the lines around 66 to not pass around values into map[] more than once, otherwise, for example, Control, which has a KeySym of 65508, doesn't get stored as 228 when it wraps around:

```
                        if (strchr(keysym,'\n')) *strchr(keysym,'\n') = '\0';
	                if (!(map[temp] = XKeysymToKeycode(xdp,XStringToKeysym(keysym)))) {
                                fprintf(stderr,"No keycode for keysym '%s'\n",keysym);
```
